<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHYHhcCq\SimpleSAML_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHYHhcCq/SimpleSAML_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerHYHhcCq.legacy');

    return;
}

if (!\class_exists(SimpleSAML_KernelProdContainer::class, false)) {
    \class_alias(\ContainerHYHhcCq\SimpleSAML_KernelProdContainer::class, SimpleSAML_KernelProdContainer::class, false);
}

return new \ContainerHYHhcCq\SimpleSAML_KernelProdContainer([
    'container.build_hash' => 'HYHhcCq',
    'container.build_id' => 'f1e2fbeb',
    'container.build_time' => 1751908659,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHYHhcCq');
