services:
  web:
    environment:
      - TZ=America/New_York
      - APP_HOME=/drupal-netbadge
      - SIMPLESAMLPHP_CONFIG_DIR=/var/simplesamlphp/config
    volumes:
      # Mount SimpleSAMLphp config
      - "../saml-config/simplesamlphp/config:/var/simplesamlphp/config"
      - "../saml-config/simplesamlphp/metadata:/var/simplesamlphp/metadata"
      - "../saml-config/simplesamlphp/cert:/var/simplesamlphp/cert"
      - "../saml-config/simplesamlphp/tmp:/var/simplesamlphp/tmp"
      - "../saml-config/simplesamlphp/log:/var/simplesamlphp/log"
      - "../saml-config/simplesamlphp/data:/var/simplesamlphp/data"
